### PR TITLE
Dynamicall choosing the most affordable metro to create harvester infra

### PR DESCRIPTION
**Pull request by rajeshkio**
Dynamically choosing the most affordable metro to create harvester infra

### CODE REVIEW

**Comment by dnoland1** [comment]
@rajeshkio another merge conflict needs to be addressed. We removed .drone.yml.

**Comment by rajeshkio** [comment]
> @rajeshkio another merge conflict needs to be addressed. We removed .drone.yml.

Removed.drone.yaml?

**Comment by rajeshkio** [comment]
> > @rajeshkio another merge conflict needs to be addressed. We removed .drone.yml.
> 
> Removed.drone.yaml?



> > @rajeshkio another merge conflict needs to be addressed. We removed .drone.yml.
> 
> Removed.drone.yaml?



> @rajeshkio another merge conflict needs to be addressed. We removed .drone.yml.

Done

**Review by dnoland1 — APPROVED** [review]
LGTM

**Pull request merged**
