### PR TITLE
iPXE for v1.3.0-rc1

### PR DESCRIPTION
**Pull request by dnoland1**

### CODE REVIEW

**Comment by rajeshkio** [comment]
I tried to create, but it kept failing.

`FlexBoot v3.6.403 (PCI 02:00.1) starting execution...ok                         e established.
FlexBoot initialising devices...                                                
Initialising completed.                                                         
                                                                                
                                                                                nown hosts.
FlexBoot v3.6.403                                                               
Features: DNS HTTP HTTPS iSCSI TFTP VLAN ELF MBOOT PXE bzImage COMBOOT Menu PXEX
T                                                                               
net0: b8:ce:f6:04:90:11                                                         
Using ConnectX-4Lx on 0000:02:00.1 (open)                                       
  [Link:up, TX:0 TXE:0 RX:0 RXE:0]                                              
Configuring (net0 b8:ce:f6:04:90:11)............................................
................ No configuration methods succeeded (http://ipxe.org/040ee119)  
No more ports. Exiting FlexBoot...                                              
                                                                                
                                                                                
Intel(R) Boot Agent GE v1.4.04                                                  
Copyright (C) 1997-2012, Intel Corporation                                      
                                                                                
PXE-E61: Media test failure, check cable                                        
PXE-M0F: Exiting Intel Boot Agent.                                              
                                                                                
Reboot and Select proper Boot device                                            
or Insert Boot Media in selected Boot device and press a key      `

**Comment by dnoland1** [comment]
@rajeshkio What value did you set for `ipxe_script` in your terraform.tfvars?

**Comment by rajeshkio** [comment]
> @rajeshkio What value did you set for `ipxe_script` in your terraform.tfvars?

We don't set it in terraform.tfvars now, right? 

`harvester_version = "v1.3.0-rc1"
hostname_prefix   = "rajesh-harvester"
node_count        = "2"
project_name      = "Harvester Labs"
plan              = "c3.small.x86"
max_bid_price     = "0.17"
metro = "SV"
spot_instance     = true
ssh_key           = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4ScCbHjmbnSJmAMVlbRP2552uFncwdGCVFHKIx5tSjMK84e8aibUcX5fdDfLdvvQcOpwL837MQEq9L60vqiS5cPlSg+P4gJ/39v3xL4TVzTWFSehDywM0ifDCTepqQIOZIneHJkdX9PxijYHFc3J0T19WeHWW5M+MIegfSJF5qVjaL1XCGPfHlBnvV5oyhsVnunFFS/kz22BCiPDv9KRLcjJVF9jKOP4U7dH3Ym2SH3KxhOlFcY6bzhJ0+fyfyYRXzeA4QDWIvrP+tr8tEdsKftUI04FtuROgIJgcSGN0cBEqt5W4dNf4Pvv9M1lBi8fQ8VjE8CXBT2VFW9VkuDSfbQb2Ki0Tz7A+e1c+wM9C/DQ5vCv8ImMePVFVTiHWA1/zIg2T1XLx4wBGFyzYCHQWhVxNuxBotqWPOh4x5Z8G+QyhAuiuOtAxfe//5In59wrs0+OraqQ1AsuYcBfN4R1GNvUKvaBnmWeYuiOh5OfxZqDyzBkfCmgXVQbiUIuvKjc= rajesh@rajesh-infracloud"
#ipxe_script       = "https://raw.githubusercontent.com/rajeshkio/test-harvester-ipxe/main/ipxe-"
num_of_vlans = 2
`

**Comment by dnoland1** [comment]
You going to have to set it there. Until the PR is merged, the script is not there for you to test. Setting it to `https://raw.githubusercontent.com/rancherlabs/harvester-equinix-terraform/9e9f20036143cd434dba6c5ae0de3a628a65c699/ipxe/ipxe-` should work.

**Comment by rajeshkio** [comment]
> You going to have to set it there. Until the PR is merged, the script is not there for you to test. Setting it to `https://raw.githubusercontent.com/rancherlabs/harvester-equinix-terraform/9e9f20036143cd434dba6c5ae0de3a628a65c699/ipxe/ipxe-` should work.

Stupid me. Yeah. I was testing in the branch, so I thought I don't need to. I forgot that the variable.tf points to the main branch.

**Review by rajeshkio — APPROVED** [review]
LGTM. Tested with a 2 node cluster

**Pull request merged**
